### ISSUE TITLE
Update Vector Tile Data

### ISSUE THREAD

**Issue by mmolta** [dvrpc/crash-data-tool#7]
Remove the following information from the vector tiles:

- **PennDOT fields**:
    TOT_INJ_CO

Update to just include CRN for lookup and MAX_SEVERI for colors

**Comment by rbeatty1** [comment]
Throwing in a vote against putting all of this in the vector tiles, rather than just doing a lookup based on crash_id to grab the relevant info from the DB return

**Comment by mmolta** [comment]
I agree, was just putting info from Marco's email into issues without much thought. The way we discussed on Slack makes sense and we'll move forward with that

**Comment by rbeatty1** [comment]
feel free to assign this to me. I'll update them to remove TOT_INJ_CO and replace it with MAX_SEVERITY
